home:
    path: /
    defaults:
        _controller: TestController::home

sub:
    prefix: sub/
    resource: "subroutes.yml"

secured:
    prefix: secured/
    resource: "secured.routes.yml"

twig:
    prefix: twig/
    resource: "twig.routes.yml"

domain.test.localhost:
    path: /domain
    host: localhost
    defaults:
        _controller: TestController::domainLocalhost

domain.test.baidu:
    path: /domain
    host: baidu.com
    defaults:
        _controller: TestController::domainBaidu

cors.home:
    path: /cors/home
    defaults:
        _controller: TestController::corsHome

cors.put:
    path: /cors/put
    methods: [PUT]
    defaults:
        _controller: TestController::corsHome

param.domain:
    path: /param/domain
    host: "{game}.baidu.com"
    defaults:
        _controller: TestController::paramDomain

param.id:
    path: "/param/id/{id}"
    host: "{game}.baidu.com"
    defaults:
        _controller: TestController::paramId
    requirements:
        id: \d+

param.slug:
    path: "/param/id/{slug}"
    host: "{game}.baidu.com"
    defaults:
        _controller: TestController::paramSlug
    requirements:
        slug: .*
param.injected:
    path: "/param/injected"
    defaults:
        _controller: TestController::paramInjected
param.injected2:
    path: "/param/injected2"
    defaults:
        _controller: TestController::paramInjectedWithInheritedClass

param.chained:
    path: "/param/chained/{id}"
    defaults:
        _controller: TestController::paramChained

cookie.setter:
    path: "cookie/set"
    defaults:
        _controller: TestController::cookieSetter
cookie.checker:
    path: "cookie/check"
    defaults:
        _controller: TestController::cookieChecker
